### ISSUE TITLE
 @GET("/nudge/api/{version}/users/@me") 404 error

### ISSUE THREAD

**Issue by alin100** [Jawbone/UPPlatform_Android_SDK#2]
Calling  @GET("/nudge/api/{version}/users/@me") response 404

11-11 16:07:45.369: D/Retrofit(4850): <--- HTTP 404 https://jawbone.com/nudge/api/v.1.1/users/@me (256ms)

D/Retrofit(4850): {"meta": {"error_detail": "Unsupported API version 1.1, unless called with an OAuth header", "code": 404, "error_type": "endpoint_error", "time": 1415693264, "message": "Not Found", "user_xid": ""}, "data": {}}

**Comment by dkpetkova** [comment]
What is the solution here?
